apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sms
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student_db
  CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:5173
