apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sms
  labels:
    app: sms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-backend
  template:
    metadata:
      labels:
        app: sms-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: postgres
                topologyKey: kubernetes.io/hostname
      containers:
        - name: backend
          image: ${IMAGE_BACKEND}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 320Mi
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=50.0 -XX:+UseSerialGC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /api/students/stats
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/students/stats
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
